### ISSUE TITLE
C0 standalone.

### ISSUE THREAD

**Issue by Aleod-m** [graphitemaster/codin#3]
I watched the video showing the C0 concept. And wanted to try it for my personal language. The thing is i use rust for my parser and lexer.
Would it be possible to provide a complete C0 file for all the primitives ?

**Comment by daurinak** [comment]
Hello after reading the https://github.com/graphitemaster/codin/blob/main/doc/C0.md file, it's not clear to me how C0 handle function pointers (as parameters, and when they are actually called). Could you be so kind as to clarify, or point me to some resource that would do that ?

**Comment by graphitemaster** [comment]
Closing this issue for now. Need to respec C0 and how it works. I'm probably going to rename it too since it confuses people.

**Comment by stianhoiland** [comment]
This project is so interesting, I wish it had more documentation. I've scoured the Internet for more info, but there is nothing. Here's the old [C0.md](https://github.com/graphitemaster/codin/blob/f07fb34ca419fa5d9b33b4dcbf9b4bf81ae6fc67/doc/C0.md) for those who missed it (and yeah, as suggested, I guess the content of that document is no longer representative).

I'm also interested in what you're doing here as a standalone solution. But, from a recent comment of yours, I'm taking a wild guess that this project is sort-of moving away from a standalone "C0" (lovely name btw!) and becoming more Odin-specific:

> the subset of C we will compile to will not be strictly standard C and rely on specific compiler flags and or extensions to ensure correctly generated code

**Comment by stianhoiland** [comment]
Found some more info regarding this project from gingerBill here:
https://www.youtube.com/watch?v=uoNirxyOfmI&t=25m50s
and here:
https://www.youtube.com/watch?v=uoNirxyOfmI&t=1m31s

In short, this project is abandoned or superseded for use in Odin by Tilde / [Cuik ](https://github.com/RealNeGate/Cuik)
